### ISSUE TITLE
valid-requirement-nodes API is not returning all node instances satisfying a requirement

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SODALITE-EU/semantic-reasoner#11]
The IDE uses this API
`http://160.40.52.200:8084/reasoner-api/v0.6/valid-requirement-nodes?requirement=host&nodeType=sodalite.nodes.DockerizedComponent`
to offer content assistance to the user when selecting a node that satisfy the _host_ requirement in a DockerizedComponent node instance.
However, this API invocation only returns one instance _snow-vm_, while there are more in the KB that matches.
There is one identical functionality in the KB Reasoner that works well. When the AADM is saved, with a node instance not satisfying the _host_ requirement, the _saveAADM_ API returns a list of suggestions to fulfill the _host_ requirement, and this list of suggestion does return the complete list of candidates, unlike the _valid-requirement-nodes_ API.

**Comment by zoevas** [comment]
Done and deployed on the server. Could you verify that it is working?

**Comment by jesus-gorronogoitia** [comment]
it works like a charm, ehjaristo!
