### ISSUE TITLE
Optimization dsl - defining rules for semantic reasoner to validate the performance models

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/semantic-reasoner#15]
Hello @kartshy , @jesus-gorronogoitia ,

I am creating this issue so as to have a high level overview for the optimization dsl for M24.

**Q1:** Will the **rules** be _dynamically_  sent to the reasoner for validating the performance models?
**Q2:** _Do you know why are the rules dynamically changing ?_ 
**Rules**
A rule is, for example, for **tensorflow**:
`num_gpus > 0  AND xla:false ---> action: xla:true`

**Q3:** _Are we in the same page about the definition of rules? If not, what is your approach ?_

**How will those rules be sent to the reasoner?**
One option could be a language for rules to be designed, so as the IDE user to have a separate editor for creating rules and 
send them to the KB reasoner.
**Q4:** _Do you have other option in mind?_

Finally, I understand the reasoner implementation for validating optimization model should be changed, since
the representation of optimization dsl will be simplified according to https://github.com/SODALITE-EU/application-optimisation/issues/12.

Note: The optimization dsl will be improved for AI training and HPC, and AI inference and data management new app types will be introduced.

Please add your thoughts, and correct me if you have a different perception for the above points.

Thanks!

**Comment by kartshy** [comment]
Q1: No it wont change dynamically. I idea is to have a file that specifies the rules and we can change and update easily. We can come up with the files format and export to reasoner when ever new rules are added or updated. You can also fetch the rules from the table (in iac model repo).

Q2: The rules wont change dynamically during deployment. 

Q3: I am not expert in this. If there is no existing solutions, we can design a simple language for rules.

Q4: No. But the idea is to have some rules like that in outlook or some thing like this https://www.npmjs.com/package/json-rules-engine

The DSL will be simplified and the we  need to move all rules to a file based definition. The semantic reasoner should be able to import rules and use them for validation and move away from the hard coded validation. The reasoner need not even know the DSL if it is designed correctly.

This is my opinion. I am open to any ideas.

**Comment by alazzaro** [comment]
We can close this issue, now outdated
