### ISSUE TITLE
Meaningful errors returned by the reasoner - (internal errors)

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/semantic-reasoner#3]
There are many cases where the reasoner returns _500 Internal server error._ 
It is better to return a meaningful message to the IDE user. This message could notify the user
about the kind of the error. If the error is caused by the aadm, the user is requested to fix it,
otherwise he can contact the KB administrator. 

For example, with the current functionality, an internal server error is thrown, when the type sodalite.nodes.DockerizedComponent does not exist in the KB: 
**AADM**
```
:Template_5
  rdf:type exchange:Template ;
  exchange:name "skyline_alignment" ;
  exchange:type "sodalite.nodes.DockerizedComponent" ;
```
**TODO: Firstly, we should create a list with all the possible errors.**

**Comment by jesus-gorronogoitia** [comment]
Great feature, I suggest to report these exceptions not as a HTTP 500 exception, but as a normal response with error notifications, that prevent the model to be stored in the KB.

**Comment by zoevas** [comment]
Hello @jesus-gorronogoitia 

I wrote the cases when there is an error in the aadm or in the resource model. 
**When an error exists in an aadm, a  400 Bad Request  response could be returned with a message indicating the kind of the error.**

Below, you can find a proposition with all the error cases located till now and the text messages that could be returned for them.
Templates section includes the error cases that could be occurred when saving an aadm, and Resource section includes the error cases that could be occurred when saving a resource model.

Feel free to share your thoughts if you want a different format in the error message, or suggest something else.

# TEMPLATES

**1. Template xxxxx:  No 'name' defined for template: XXXX**
Caused when   _`exchange:name "snow-webcam-crawler" ;`_   is missing.
**2. Template xxxxx:  No 'type' defined for template: xxxx**
Caused when  _`exchange:type "sodalite.nodes.DockerizedComponent" ;`_  is missing
**3. Template xxxxx:  xxxxxx type  does not exist** 
Caused when a template is of a type that is not stored in KB
_`exchange:type "xxxxxx" ;`_

### REQUIREMENTS

**4. Template xxx: No 'name' defined for requirement**

```
:Requirement_20
  rdf:type exchange:Requirement ;
 # ----> THIS IS NOT DEFINED exchange:name "dependency" ;
  exchange:value "snow-docker-host" ;
```

**5. Template xxx: Cannot find "xxx" requirement property** 
**Example**
```
 :Requirement_20
  rdf:type exchange:Requirement ;
  exchange:name "dependency" ;
  exchange:value "snow-docker-host" ;
.
```

dependency property might have not been defined in any resource model in KB.
In that case, an error with the above message is sent to IDE
 **Message:** 

> skyline-extractor template: Cannot find "dependency" requirement property 

**6. Template xxx: Cannot find "xxxx" requirement parameter**  
**Example**
```
 vehicle-iot-vm:  
		requirements:
			protected_by: 
				node: security-rules-vehicle-iot-full
							
```
**Message:** 

> vehicle-iot-vm template: Cannot find "node" requirement parameter 

**7. Template xxx:  No 'name' defined for requirement parameter**
```
:Parameter_1
  rdf:type exchange:Parameter ;
  "exchange:name "node" ; <---- is missing
  exchange:value 'security-rules-vehicle-iot-full' ;
.

```

### PROPERTIES
**8. Template xxx: No 'name' defined for property**

e.g.   exchange:name "ports"  is missing
```
:Property_1
  rdf:type exchange:Property ;
  exchange:listValue "80:80" ;
.
```


### CAPABILITIES

**9.) Template xxx: No 'name' defined for capability**
```
:Capability_1
  rdf:type exchange:Capability ;
  #exchange:name "job" ; <-- is missing
  exchange:hasParameter :Parameter_225 ;
  exchange:hasParameter :Parameter_226 ;
.
```

**10. xxx template: Cannot find capability: xxx**
**Example**
```
optimization-vm:
    ....
    capabilities:
			host:
```
				
					
**Message:** 

> optimization-vm template: Cannot find capability: host

**11. xxx template: Cannot find xxx template for 'xxxx' capability**
```
template_a:
...
capabilities:
			host:
					xxxx
```

**Message:**

>  template_a template: Cannot find xxx template for 'host' capability


### INPUTS

**12. xxx template: No 'name' defined for input: xxxx**
exchange:name xxx is missing

# RESOURCE MODEL

**1. No 'name' defined for type: XXX**
Caused when    _`exchange:name "sodalite.nodes.ConfigurationDemo" ;`_   is missing.
  
 **2. "No 'derivesFrom' defined for type: xxxx**
 Caused when  _`exchange:derivesFrom "tosca.nodes.SoftwareComponent" ;`_  is missing
 
 **3.  xxx Type: Derived type xxxxxx does not exist**
Caused when a node/relationship/capability type derives from a type that is not stored in KB
_`exchange:derivesFrom "tosca.nodes.SoftwareComponent" ;`_

### CAPABILITIES
**4. xxx type: No 'name' defined for capability**

e.g.	
```
:Capability_401
  rdf:type exchange:Capability ;
  #exchange:name "configured_job" ; <--- THIS LINE DOES NOT EXIST
  exchange:hasParameter :Parameter_460 ;
  exchange:hasParameter :Parameter_461 ;
```
.

**5. xxx type: Cannot find xxx  type for  'xxxx' capability**
e.g. 
```
sodalite.nodes.hpc.job.torque.result: 
 capabilities:
      job:
        type: sodalite.capabilities.hpc.CompleteJob
```
**Message:**   

> sodalite.nodes.hpc.job.torque.result type: Cannot find sodalite.capabilities.hpc.CompleteJob for "type" capability

### PROPERTIES
**6. xxx Type: No 'name' defined for property**

e.g.   exchange:name "mysql_db_pass"  is missing
```
:Property_1
  rdf:type exchange:Property ;
  # exchange:name "mysql_db_pass" ; <--- MISSING
  exchange:description 'MYSQL database password' ;
  exchange:hasParameter :Parameter_22 ;
.
```

### INTERFACES
**7. xxx Type: No 'name' defined for interface**
_`exchange:name "xxx" ;`_ is missing
**8. Cannot find type: xxx for interface**
e.g. in case tosca.interfaces.node.lifecycle.Standard does not exist in KB, or in the local resource model
```
interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
```

### REQUIREMENTS
**9.  xxx Type: No 'name' defined for requirement**
_`exchange:name "xxx" ;`_ is missing
**10.  xxx type: Cannot find xxx  type for  'xxxx' requirement**

e.g.
```
sodalite.nodes.hpc.job.torque.configuration.node
 requirements:
      - job_node:
          node: tosca.nodes.Compute
```
          
          
 **Message:**   

> sodalite.nodes.hpc.job.torque.configuration.node type: Cannot find tosca.nodes.Compute for "node" requirement

**Comment by zoevas** [comment]
It has been done. But it is pending to include path to the context so as IDE to mark as red the wrong element:

 name contains the name of the missing element
"type": "MappingException",
            "info": {
                "name": "registry",
                "context": "prometheus-container",
                "description": "Cannot find requirement property"
            }

 context should be prometheus-container/properties

**Comment by zoevas** [comment]
@jesus-gorronogoitia 

On CERTH server, I deployed the reasoner that returns a correct path (_context_) for the ide in a case of an error. Also, I ll deploy it on the testbed today.

You could try to save a template with a type that does not exist OR  assign to a requirement a template that do not exist.
And then we can verify if the ide can show the error to the user.

We discussed that offline, I am just commenting here for having it in the history and once it works I ll close the issue.
