### ISSUE TITLE
Support the storage of all node types defined within a RM in the case any of them refer to types not available in the KB but specified in the same RM

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SODALITE-EU/semantic-reasoner#4]
When saving a RM into the KB, in the case that types defined within the KB are referencing to each other (within the same RM) but not to types already available in the KB, they should be stored, not triggering an exception because those types are not yet available. In other words, the KB should scan the RM looking for referenced types not located in the KB before triggering an error.

**Comment by zoevas** [comment]
Done.
