### ISSUE TITLE
SubmitTOSCAService: Empty TOSCA property value causes Internal error

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/semantic-reasoner#62]
## Current behaviour
If a node_type or a node_template contains a property with empty value SubmitTOSCAService fails with internal error.
Consider a node_template that has **group_description** property undefined. 
```yaml
topology_template:

  node_templates:

    security-rules-sodalite-remote-access:  
      type: sodalite.nodes.OpenStack.TestOpenstack.SecurityRules 
      properties:
        ports:
         ports-tcp-20-22:  
            port_range_max: 22 
            remote_ip_prefix: 0.0.0.0/0
            port_range_min: 20 
            protocol: tcp
        group_name: sodalite-remote-access
        group_description:
```
Invoking saveTOSCA with this template would cause:

<body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> java.lang.NullPointerException</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>javax.servlet.ServletException: java.lang.NullPointerException
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre><p><b>Root Cause</b></p><pre>java.lang.NullPointerException
	tosca.mapper.TOSCAMappingService.valueOrParameter(TOSCAMappingService.java:274)
	tosca.mapper.TOSCAMappingService.lambda$parseProperties$7(TOSCAMappingService.java:205)
	java.base&#47;java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	tosca.mapper.TOSCAMappingService.parseProperties(TOSCAMappingService.java:194)
	tosca.mapper.TOSCAMappingService.lambda$parseTemplates$4(TOSCAMappingService.java:159)
	java.base&#47;java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	tosca.mapper.TOSCAMappingService.lambda$parseTemplates$5(TOSCAMappingService.java:144)
	java.base&#47;java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	tosca.mapper.TOSCAMappingService.parseTemplates(TOSCAMappingService.java:140)
	tosca.mapper.TOSCAMappingService.lambda$parseDocument$0(TOSCAMappingService.java:77)
	java.base&#47;java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	tosca.mapper.TOSCAMappingService.lambda$parseDocument$1(TOSCAMappingService.java:74)
	java.base&#47;java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	tosca.mapper.TOSCAMappingService.parseDocument(TOSCAMappingService.java:56)
	tosca.mapper.TOSCAMappingService.parse(TOSCAMappingService.java:52)
	restapi.tosca.mapper.SubmitTOSCAService.saveTOSCA(SubmitTOSCAService.java:91)
	jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	java.base&#47;jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base&#47;java.lang.reflect.Method.invoke(Method.java:566)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.40</h3></body></html>

## Expected behaviour
TOSCA is saved without errors.

**Comment by alexmaslenn** [comment]
Well technically YAML allows a node value to be undefined. xOpera will parse these values as `null`.
If it is not a minor problem then we can try to avoid empty values in PDS output and deal with it later.
But in general it is a good thing to have this option.

**Comment by zoevas** [comment]
I fixed it... I ll merge it to the master. And ideally deploy that on testbed. I have some issues with the graphdb, I cannot access it on testbed through the url.
Also you can test it on CERTH server.

**Comment by zoevas** [comment]
I think it is fixed. If not, re-open the issue. Thanks.
