### ISSUE TITLE
Store complete RM models into the KB, including those that declares and references types within the model

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SODALITE-EU/semantic-reasoner#8]
Current KB Reasoner implementation does not support the storage of RMs that declares and references types within the model. Then, if a RM declares a node type for instance and reference it in another type, it cannot be store into the KB, as the KB Reasoner breaks. Please fix this, so that any compliant RM could be stored into the KB.

**Comment by zoevas** [comment]
I have prepared  a fix for this issue. With this fix, if a node type references another type that is defined within this local resource model, KB does not break.  If the referenced node type exists neither in KB nor in the local resource model, reasoner breaks.


For example _sodalite.nodes.hpc.job.torque.configuration_ should be defined within the local resource model, or should be already stored in KB.

```
:Node_1
  rdf:type exchange:Node ;
  exchange:description 'torque job configuration' ;
  exchange:name "sodalite.nodes.hpc.job.torque.configuration.node" ;
  exchange:derivesFrom "sodalite.nodes.hpc.job.torque.configuration" ;
```

The fix has been developed locally. Before deploying it on the server http://160.40.52.200/ and push the changes to the master, it is needed to be tested locally. Thus, **a resource model is needed in ttl exchange format that has references in node types that are defined within this local model.** 
@jesus-gorronogoitia Could you prepare a model for the sake of testing? Thanks

**Comment by zoevas** [comment]
Done.
