### ISSUE TITLE
KB should be pre-initialized with all TOSCA normative types including primitive types

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SODALITE-EU/semantic-reasoner#9]
IDE requires a KB reasoner API to  get all TOSCA normative types, including node (this API already exists), data, capabilities, relationships, etc. For instance, primitive data types such us string, integer, etc should be retrieved KB.

**Comment by zoevas** [comment]
@jesus-gorronogoitia is this done? I think yes. We created the /types api by passing the imported namespaces and the kind of type to be searched:
http://localhost:8080/reasoner-api/v0.6/types;imports=snow;imports=docker;type=data

If you agree, I can close the issue.
